name: CI

on:
  push:
    branches:
      - idea212.x
      - idea213.x
      - idea221.x
      - idea222.x
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.11"

      - name: Run tests
        run: sbt test
        shell: bash
